// Enum cho Category
export enum ProductCategory {
  CAR = 'CAR',
  PART = 'PART'
}

// Enum cho Status
export enum ProductStatus {
  AVAILABLE = 'AVAILABLE',
  SOLD = 'SOLD',
  OUT_OF_STOCK = 'OUT_OF_STOCK'
}

export enum PartType {
  ENGINE = 'ENGINE',
  TRANSMISSION = 'TRANSMISSION',
  BRAKE_SYSTEM = 'BRAKE_SYSTEM',
  SUSPENSION = 'SUSPENSION',
  ELECTRICAL = 'ELECTRICAL',
  COOLING_SYSTEM = 'COOLING_SYSTEM',
  FUEL_SYSTEM = 'FUEL_SYSTEM',
  EXHAUST_SYSTEM = 'EXHAUST_SYSTEM',
  BODY_PARTS = 'BODY_PARTS',
  INTERIOR = 'INTERIOR',
  EXTERIOR = 'EXTERIOR',
  TIRES_WHEELS = 'TIRES_WHEELS',
  LIGHTING = 'LIGHTING',
  FILTERS = 'FILTERS',
  BELTS = 'BELTS',
  BATTERIES = 'BATTERIES',
  STEERING = 'STEERING',
  AIR_CONDITIONING = 'AIR_CONDITIONING',
  SAFETY = 'SAFETY',
  OTHERS = 'OTHERS'
}
